fork = false
frame = "none"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false


[font]
normal = ["JetBrainsMono Nerd Font"]
size = 13
