fork = false
# frame = "full"
frame = "none"
idle = true
maximized = true
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = false
wsl = false

[font]
normal = [] # Will use the bundled Fira Code Nerd Font by default
size = 14.0
